#!/bin/env python
from micropython_firmware_serial import serial_interface_qobject
import sys
import signal
from PyQt5 import QtCore



class QApplication(QtCore.QCoreApplication):
    def __init__(self, *argv):
        super().__init__(*argv)

        self.serial = serial_interface_qobject.SerialInterface("/dev/ttyUSB0")
        self.serial.messageChanged.connect(self.onMessage)
        self.serial.reset()
        self.qt = QtCore.QTimer()
        self.index = 0
        self.qt.timeout.connect(self.update)
        self.qt.start(1000)

    def onMessage(self, message):
        sys.stdout.write(message)
    
    def update(self, *args):
        self.index += 1
        message = "C %d\r" % (self.index % 2)
        print(message)
        self.serial.write(message)

def main():

    signal.signal(signal.SIGINT, signal.SIG_DFL)
    app = QApplication(sys.argv)    
    app.exec()

if __name__ == '__main__':
    main()